import ManagerTemplate from "../../../components/managerTemplate"
import adminList from "../adminlist"

export const metadata = {
   title: 'Kos Admin | Admin',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <ManagerTemplate title="Kos Anda" id="kosadmin" menuList={adminList}>
           {children}
       </ManagerTemplate>

       
   )
}

export default RootLayout
