import ManagerTemplate from "../../../components/managerTemplate"
import societylist from "../societylist"

export const metadata = {
   title: 'Dashboard | Society',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <ManagerTemplate title="Dashboard" id="dashboard" menuList={societylist}>
           {children}
       </ManagerTemplate>

       
   )
}

export default RootLayout
