import ManagerTemplate from "../../../components/managerTemplate"
import societylist from "../societylist"

export const metadata = {
   title: 'Pesanan | Society',
   description: 'Generated by create next app',
}

type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <ManagerTemplate title="Pesanan" id="pesanan" menuList={societylist}>
           {children}
       </ManagerTemplate>

       
   )
}

export default RootLayout
