import ManagerTemplate from "@/components/managerTemplate";
import adminList from "../adminlist"

export const metadata = {
   title: 'Akun | Admin',
   description: 'Generated by create next app',
}
type PropsLayout = {
   children: React.ReactNode
}

const RootLayout = ({ children }: PropsLayout) => {
   return (
       <ManagerTemplate title="Akun" id="akun" menuList={adminList}>
           {children}
       </ManagerTemplate>

       
   )
}

export default RootLayout
